### ISSUE TITLE
Pull In Google authenticator Code using Composer Manager

### ISSUE THREAD

**Issue by aweingarten** [d8-contrib-modules/tfa_basic#2]
Currently the module is deployed with a copy of the google authenticator source code.  The standard in D8 is to include third-party code using composer.   This will allow the module to quickly and easily provide updates.  It will also prevent conflicts with other module that may use authenticator for other tasks.

**Comment by therealssj** [comment]
Addressed in PR https://github.com/d8-contrib-modules/tfa_basic/pull/9
